import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/component/navbar";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portofolio - Resky Adhyaksa",
  description: "Generated by Me",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} antialiased`}
      >
        <div className="fixed top-4 z-1000 flex w-full justify-center">
          <NavigationBar pathname={"Resky Adhyaksa"} />
        </div>
        {children}
      </body>
    </html>
  );
}
