import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/component/navbar";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portofolio - Resky Adhyaksa",
  description: "Generated by Resky",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} antialiased`}>
        <div className="fixed top-3 sm:top-5 z-50 flex w-full justify-center px-3 sm:px-6 pointer-events-none">
          <div className="pointer-events-auto">
            <NavigationBar />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
